#if DEBUG
  import Foundation
  import SwiftData

  /// Decodes the per-locale App Store screenshot demo-content catalog and seeds an
  /// in-memory store with it.
  ///
  /// The catalog lives in the UI **test** target
  /// (`simple-recurring-budgetsUITests/ScreenshotSeeds/<locale>.json`, generated by the
  /// `scripts/screenshot_content/` pipeline). The `AppStoreScreenshots` UI test reads the
  /// file matching the launch language and passes its contents to the app via the
  /// `SEED_SCREENSHOTS_JSON` launch-environment variable; `InMemoryModelContainer.makeForUITests()`
  /// decodes it here. DEBUG-only — these marketing fixtures never ship in a Release build.
  ///
  /// Structural fields (`period`, `startOffsetDays`, `isCarryOverEnabled`, expense `daysAgo`)
  /// mirror `scripts/screenshot_content/SOURCE.json`; `startOffsetDays` backdates a budget far
  /// enough that the live carry-over walker produces a visible surplus chip.
  struct ScreenshotSeed: Decodable {
    struct SeedBudget: Decodable {
      let name: String
      let icon: String?
      let period: String
      let currencyCode: String
      let allocation: String
      let startOffsetDays: Int
      let isCarryOverEnabled: Bool
      let expenses: [SeedExpense]
    }

    struct SeedExpense: Decodable {
      let name: String?
      let amount: String
      let daysAgo: Int
    }

    let budgets: [SeedBudget]

    /// Decode a catalog JSON string, or nil if it is missing/malformed.
    static func decode(from json: String) -> ScreenshotSeed? {
      guard let data = json.data(using: .utf8) else { return nil }
      return try? JSONDecoder().decode(ScreenshotSeed.self, from: data)
    }

    /// Build `Budget` / `ExpenseItem` / `AllocationChange` models from the seed and insert
    /// them, mirroring `DebugData.seed(into:)`.
    func seed(into context: ModelContext, now: Date = Date()) {
      let cal = Calendar.current
      let dayStart = cal.startOfDay(for: now)
      for seed in budgets {
        let period = BudgetPeriod(rawValue: seed.period) ?? .daily
        let budget = Budget(
          name: seed.name,
          currencyCode: seed.currencyCode,
          period: period,
          isCarryOverEnabled: seed.isCarryOverEnabled,
          icon: seed.icon
        )
        let startDate = cal.date(byAdding: .day, value: -seed.startOffsetDays, to: dayStart) ?? dayStart
        budget.startDate = startDate
        budget.sortOrder = (try? Budget.nextSortOrder(for: context)) ?? 0

        let expenses = seed.expenses.map { exp in
          ExpenseItem(
            amount: Decimal(string: exp.amount) ?? 0,
            name: exp.name,
            date: cal.date(byAdding: .day, value: -exp.daysAgo, to: now) ?? now
          )
        }
        for expense in expenses {
          expense.budget = budget
        }
        budget.expenseItems = expenses

        let change = AllocationChange(effectiveFrom: startDate, amount: Decimal(string: seed.allocation) ?? 0)
        change.budget = budget
        budget.allocationChangesStorage = [change]

        context.insert(budget)
        for expense in expenses {
          context.insert(expense)
        }
        context.insert(change)
      }
      try? context.save()
    }
  }
#endif
